import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
    {
      type: "link",
      label: "Playground",
      href: "/playground/",
    },
  ],
};

export default sidebars;
